### PR TITLE
Sort by ranking

### PR DESCRIPTION
**Pull request by chrismytton**
Closes https://github.com/everypolitician/wikisnakker/issues/42

### CODE REVIEW

File: lib/wikisnakker.rb [hunk 1]
```diff
@@ -143,7 +143,7 @@ def initialize(raw)
       end]
       raw['claims'].each do |property_id, claims|
         property "#{property_id}s".to_sym do
-          claims.map { |c| Claim.new(c) }
+          claims.map { |c| Claim.new(c) }.sort { |a, b| b.rank <=> a.rank }
```
Comment (tmtmtmtm) [inline lib/wikisnakker.rb]: I think this should really have a comment to make it obvious that it's relying on the fact that the ranks happen to sort in reverse alphabetical order; otherwise a future reader will likely spend too much time scratching their head at what wizardry is going on here!

Comment (tmtmtmtm) [inline lib/wikisnakker.rb]: Also, can't this just be `.sort_by(&:rank)`?

**Comment by tmtmtmtm** [comment]
Conceptually looks good, though I'm not sure what's going on with the test failures

**Comment by tmtmtmtm** [comment]
The logic seems weird to me now. If I'm reading this right, it says: if there's only one rank, return all the existing data 'as is'. If, however, there are claims at different ranks, sort the claims by rank, and then reverse them.

But this means that if the claims are:  "preferred: P1=A; normal: P2=B, P3=C; deprecated: P4=D" they're going to come back in order: P1=A, P3=C, P2=B, P4=D, whereas I'd really expect them come back as: P1=A, P2=B, P3=C, P4=D

Perhaps this should instead be something more like:

```ruby 
property "#{property_id}s".to_sym do
    claims.map { |c| Claim.new(c) }.group_by(&:rank).sort_by { |r, cs| r.reverse }.flat_map { |r, cs| cs }
end
```

(NB the existing code took me quite a bit longer to grok that I would like, because it wasn't immediately obvious that `property` here is a method-generating-method that takes the block as a second argument, rather than this being a map in void context over the results of calling `property` with the first argument. Perhaps `property` should be renamed something more explicit like `define_property_method`?)

File: lib/wikisnakker.rb [hunk 2]
```diff
@@ -142,11 +142,14 @@ def initialize(raw)
         [key, Sitelink.new(value)]
       end]
       raw['claims'].each do |property_id, claims|
-        property "#{property_id}s".to_sym do
-          claims.map { |c| Claim.new(c) }
+        define_property_method "#{property_id}s".to_sym do
+          # A claim's rank can be either preferred, normal or deprecated. We sort them by
+          # rank in reverse order because lexicographic ordering happens to work for the
+          # known ranks.
+          claims.map { |c| Claim.new(c) }.group_by(&:rank).sort_by { |r, _| r.reverse }.flat_map { |_, cs| cs }
```
Comment (chrismytton) [inline lib/wikisnakker.rb]: This won't work because the `r.reverse` means that the claims are actually being sorted by the reversed rank string, e.g. `lamron` instead of `normal`.

**Comment by chrismytton** [comment]
@tmtmtmtm I've updated the logic for sorting claims and added some more thorough tests, so I think this is ready for another 👀

**Comment by tmtmtmtm** [comment]
Lots of failing tests here with

```
NoMethodError: undefined method `to_h' for #<Array:0x000000049f2c08>
```

**Comment by chrismytton** [comment]
The tests on Travis seem to only be failing on Ruby 2.0.0, a quick Google reveals that ["The `to_h` method is only available in Ruby version 2.1 or higher."](http://stackoverflow.com/a/31684031)

Do we still want to support ruby 2.0.0? I guess we might do for now because it comes on OS X as the default Ruby, however support was [officially stopped 24 Feb 2016](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/).

**Comment by chrismytton** [comment]
I now realise that we have dozens of scrapers that are running on Ruby 2.0.0, so I'll change this so it works correctly on that version.

**Comment by chrismytton** [comment]
@tmtmtmtm Just pushed a fix to make this work with Ruby 2.0.0.

**Comment by tmtmtmtm** [comment]
Looks good to me! :shipit: 

(And yay for travis catching this by trying multiple Ruby versions!)

**Comment by tmtmtmtm** [comment]
Let's see what starts flowing through now that we've been picking up wrongly…
